"""=add field of parentID in commsionDetails table

Revision ID: 3e0c51b2e27
Revises: 4b366f4dedc
Create Date: 2019-10-21 12:03:49.657599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0c51b2e27'
down_revision = '4b366f4dedc'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commissionDetails', sa.Column('parentID', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_commissionDetails_parentID'), 'commissionDetails', ['parentID'], unique=True)
    op.create_unique_constraint(None, 'commissionDetails', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commissionDetails', type_='unique')
    op.drop_index(op.f('ix_commissionDetails_parentID'), table_name='commissionDetails')
    op.drop_column('commissionDetails', 'parentID')
    ### end Alembic commands ###
