"""=chage type of the isDisable filed in the commmissionDetails table

Revision ID: 4a17a930360
Revises: 5aebd49de55
Create Date: 2019-10-21 12:39:44.287403

"""

# revision identifiers, used by Alembic.
revision = '4a17a930360'
down_revision = '5aebd49de55'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    pass
    ### end Alembic commands ###
