"""=create commissionDetails table

Revision ID: 4b366f4dedc
Revises: 34d93158f03
Create Date: 2019-10-21 11:50:24.975367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b366f4dedc'
down_revision = '34d93158f03'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commissionDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrierID', sa.Integer(), nullable=False),
    sa.Column('productID', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=255), nullable=True),
    sa.Column('className', sa.String(length=255), nullable=True),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commission'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_commissionDetails_carrierID'), 'commissionDetails', ['carrierID'], unique=True)
    op.create_index(op.f('ix_commissionDetails_className'), 'commissionDetails', ['className'], unique=False)
    op.create_index(op.f('ix_commissionDetails_productID'), 'commissionDetails', ['productID'], unique=True)
    op.create_index(op.f('ix_commissionDetails_productName'), 'commissionDetails', ['productName'], unique=False)
    op.create_unique_constraint(None, 'employees', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_index(op.f('ix_commissionDetails_productName'), table_name='commissionDetails')
    op.drop_index(op.f('ix_commissionDetails_productID'), table_name='commissionDetails')
    op.drop_index(op.f('ix_commissionDetails_className'), table_name='commissionDetails')
    op.drop_index(op.f('ix_commissionDetails_carrierID'), table_name='commissionDetails')
    op.drop_table('commissionDetails')
    ### end Alembic commands ###
