"""=add isDisable filed in the commmissionDetails table

Revision ID: 5aebd49de55
Revises: 3e0c51b2e27
Create Date: 2019-10-21 12:13:18.892284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aebd49de55'
down_revision = '3e0c51b2e27'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commissionDetails', sa.Column('isDisabled', sa.BOOLEAN(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commissionDetails', 'isDisabled')
    ### end Alembic commands ###
